// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:project_structure/features/home/data/models/home_model.dart';
import 'package:project_structure/features/home/data/models/locale.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HomeModelAdapter());
    registerAdapter(LocaleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HomeModelAdapter());
    registerAdapter(LocaleAdapter());
  }
}
